version: "3.8"

services:
  auth_service:
    build: ./auth_service
    expose:
      - 8000

  event_service:
    build: ./event_service
    expose:
      - 8001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"   # Puerto externo 27018 -> interno 27017
    volumes:
      - mongo-data:/data/db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - event_service

volumes:
  mongo-data:
